Adds ToIoError trait and implements this trait for NetlinkPacket
polachok/pnetlink pull request #26
Opened 2017-09-21 09:03 UTC by bkchr

A NetlinkPacket can contain an error. This trait has a function that tries to convert a
NetlinkPacket to a std::io::Error.

2017-09-22 10:30 UTC, polachok requested changes
It seems like there're 2 unrelated changes here? ToIoError and add_addr().
I'd be happy to merge both if you split them into different PRs

2017-09-22 10:37 UTC, bkchr commented
Yeah, sorry for that. I will split them up.

2017-09-22 10:40 UTC, bkchr commented
Done

2017-09-23 14:41 UTC, bkchr commented
Will you merge? :)

2017-09-23 23:07 UTC, merged