Added support for nested attributes
polachok/pnetlink pull request #32
Opened 2017-11-19 13:58 UTC by elij

Good Afternoon, 

I've added the following code to use this library for creating VETH pairs -- it specifically allows nesting of attributes.

However I'm not sure if this is inline with code from this project.

Is it possible to get feedback?

Thanks

2017-11-19 14:35 UTC, bkchr requested changes
I added some comments, in general I'm unsure why we need this `Nested` enum in the project.

2017-11-19 14:35 UTC, bkchr commented on src/packet/route/route.rs
> +impl<'a> ToPayload for &'a [&'a RtAttrPacket<'a>] {
As we already implement impl<'a> ToPayload for &'a [&'a ToPayload, this implementation should already exist implicit.

2017-11-19 14:35 UTC, bkchr commented on src/packet/route/route.rs
> +impl<'a> ToPayload for Nested<'a> {
I would accept `ToPayload` for `IfInfoPacket`. If you need this enum in your project, I would say you implement it in your project. I have done the same for a project of me.

2017-11-19 14:35 UTC, bkchr commented on src/packet/route/route.rs
> +        self.len() + 1
Why plus one? I would expect that the length is encoded as is, don't know why it should have a NullByte at the end.

2017-11-19 14:35 UTC, bkchr commented on src/packet/route/route.rs
> +impl<'a> ToPayload for &'a [&'a Nested<'a>] {
Can also be dropped, as you already implement `ToPayload` for `Nested`.

2017-11-20 10:51 UTC, elij commented
Thanks I would also like to avoid adding the enum but outside of pnetlink I can't access the payload.

I need a way with a RtAttr to have a payload of an array mixed of IfInfoMsg and RtAttr (see use here: https://github.com/lypy/andover/blob/master/src/main.rs#L102)

VETH_INFO_PEER (RtAttr)
- IfInfo
- IFLA_IFNAME RtAttr)

Do you have any suggestions? I'll do the heavy lifting outside and limit the pull request to just the ifinfo payload.

2017-11-20 11:27 UTC, bkchr commented
Did you tried:
```
let mut link_info_data : Vec<&ToPayload> = Vec::new();
link_info_data.push(&n1);
link_info_data.push(&n2);

let info_peer = RtAttrPacket::create_with_payload(VETH_INFO_PEER, &link_info_data[..]);
```

Look [here](https://github.com/superscale/worm/blob/152ce141cbae111a1a91574b9af51d077436311b/src/tunnel.rs#L56) to see what I'm doing to create a big package.

2017-11-20 12:52 UTC, elij commented
Thank you very much :) 

I'll create a new pull request

2017-11-20 12:52 UTC, closed without merging